[
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/1123965476",
    "html_url": "https://github.com/expressjs/express/issues/4906#issuecomment-1123965476",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/4906",
    "id": 1123965476,
    "node_id": "IC_kwDOAAOeZ85C_lok",
    "user": {
      "login": "dougwilson",
      "id": 67512,
      "node_id": "MDQ6VXNlcjY3NTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/67512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dougwilson",
      "html_url": "https://github.com/dougwilson",
      "followers_url": "https://api.github.com/users/dougwilson/followers",
      "following_url": "https://api.github.com/users/dougwilson/following{/other_user}",
      "gists_url": "https://api.github.com/users/dougwilson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dougwilson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dougwilson/subscriptions",
      "organizations_url": "https://api.github.com/users/dougwilson/orgs",
      "repos_url": "https://api.github.com/users/dougwilson/repos",
      "events_url": "https://api.github.com/users/dougwilson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dougwilson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-11T16:01:11Z",
    "updated_at": "2022-05-11T16:01:11Z",
    "author_association": "MEMBER",
    "body": "Hi @abdallaoui-dev sorry you are having trouble. I'm not clear on what exactly you mean, though. Can you show the example does reproduces the issue that I can run and debug through it?",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/1123965476/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/1125096137",
    "html_url": "https://github.com/expressjs/express/issues/4906#issuecomment-1125096137",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/4906",
    "id": 1125096137,
    "node_id": "IC_kwDOAAOeZ85DD5rJ",
    "user": {
      "login": "abdallaoui-dev",
      "id": 91975214,
      "node_id": "U_kgDOBXtuLg",
      "avatar_url": "https://avatars.githubusercontent.com/u/91975214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abdallaoui-dev",
      "html_url": "https://github.com/abdallaoui-dev",
      "followers_url": "https://api.github.com/users/abdallaoui-dev/followers",
      "following_url": "https://api.github.com/users/abdallaoui-dev/following{/other_user}",
      "gists_url": "https://api.github.com/users/abdallaoui-dev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abdallaoui-dev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abdallaoui-dev/subscriptions",
      "organizations_url": "https://api.github.com/users/abdallaoui-dev/orgs",
      "repos_url": "https://api.github.com/users/abdallaoui-dev/repos",
      "events_url": "https://api.github.com/users/abdallaoui-dev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abdallaoui-dev/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-12T14:54:24Z",
    "updated_at": "2022-05-12T14:54:24Z",
    "author_association": "NONE",
    "body": "if someone put % in url like http://localhost:3000/see/%\r\nexpress throws URIError: Failed to decode pram /see/% with response 400\r\nnow if add the fourth argument to app.use(err, req, res, next) err does't catch it, if I remove err arg and trycatch decodeURI(req.path) it works and I can catch the error.\r\nI solve this by having two functions one for all errors and one for this which should be with all in one function\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/1125096137/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/1125205982",
    "html_url": "https://github.com/expressjs/express/issues/4906#issuecomment-1125205982",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/4906",
    "id": 1125205982,
    "node_id": "IC_kwDOAAOeZ85DEUfe",
    "user": {
      "login": "dougwilson",
      "id": 67512,
      "node_id": "MDQ6VXNlcjY3NTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/67512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dougwilson",
      "html_url": "https://github.com/dougwilson",
      "followers_url": "https://api.github.com/users/dougwilson/followers",
      "following_url": "https://api.github.com/users/dougwilson/following{/other_user}",
      "gists_url": "https://api.github.com/users/dougwilson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dougwilson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dougwilson/subscriptions",
      "organizations_url": "https://api.github.com/users/dougwilson/orgs",
      "repos_url": "https://api.github.com/users/dougwilson/repos",
      "events_url": "https://api.github.com/users/dougwilson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dougwilson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-12T16:39:11Z",
    "updated_at": "2022-05-12T16:40:04Z",
    "author_association": "MEMBER",
    "body": "Hello, thank you, that makes sense. Unfortunately I am not able to replicate what you are saying. Given your statement, I constructed the following simple app to demonstrate the error handler catching an error:\r\n```js\r\nconst express = require(\"./index\")\r\nconst app = express()\r\n\r\napp.get('/see/:param', (req, res) => {\r\n  res.send('see!')\r\n})\r\n\r\napp.use((err, req, res, next) => {\r\n  res.send('got an error in the error handler: ' + err.toString())\r\n})\r\n\r\napp.listen(3000)\r\n```\r\n\r\nRunning and then calling that with the URL you provided, `http://localhost:3000/see/%` demonstrates that the error handler does indeed get that URIError:\r\n```\r\n$ curl -s 'http://localhost:3000/see/%'\r\ngot an error in the error handler: URIError: Failed to decode param '%'\r\n```\r\n\r\nIf you can provide a concrete demonstration like I have above that shows it not being caught, we can help further.",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/1125205982/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]