[
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/19664922",
    "html_url": "https://github.com/expressjs/express/pull/1641#issuecomment-19664922",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/1641",
    "id": 19664922,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5NjY0OTIy",
    "user": {
      "login": "hacksparrow",
      "id": 950112,
      "node_id": "MDQ6VXNlcjk1MDExMg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/950112?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hacksparrow",
      "html_url": "https://github.com/hacksparrow",
      "followers_url": "https://api.github.com/users/hacksparrow/followers",
      "following_url": "https://api.github.com/users/hacksparrow/following{/other_user}",
      "gists_url": "https://api.github.com/users/hacksparrow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hacksparrow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hacksparrow/subscriptions",
      "organizations_url": "https://api.github.com/users/hacksparrow/orgs",
      "repos_url": "https://api.github.com/users/hacksparrow/repos",
      "events_url": "https://api.github.com/users/hacksparrow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hacksparrow/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-19T06:13:23Z",
    "updated_at": "2013-06-19T06:13:23Z",
    "author_association": "MEMBER",
    "body": "Sorry for the delayed response, been kinda busy. The latest update should fix it.\n\nThis issue is not related to the error() function. It is encountered when a 304 response is to be sent to the user agent. In such cases, the 'stream' event is not fired, which causes the callback not to be executed.\n\nSince 200 and 304 responses both fire the 'finish' event, I have moved the callback trigger to the 'finish' event handler so that the callback is executed for both 200 and 304 responses.\n\nThe error() function is working fine as expected and is not touched.\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/19664922/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]